// import 'package:cloud_firestore/cloud_firestore.dart';

// class ChatMessage {
//   final String id;
//   final String senderId;
//   final String receiverId;
//   final String text;
//   final DateTime timestamp;

//   ChatMessage({
//     required this.id,
//     required this.senderId,
//     required this.receiverId,
//     required this.text,
//     required this.timestamp,
//   });

//   factory ChatMessage.fromMap(Map<String, dynamic> map, String id) {
//     return ChatMessage(
//       id: id,
//       senderId: map['senderId'],
//       receiverId: map['receiverId'],
//       text: map['text'],
//       timestamp: (map['timestamp'] as Timestamp).toDate(),
//     );
//   }

//   Map<String, dynamic> toMap() => {
//         'senderId': senderId,
//         'receiverId': receiverId,
//         'text': text,
//         'timestamp': timestamp,
//       };
// }


// ------Updated with camera images and saved images code-----------------------
import 'package:cloud_firestore/cloud_firestore.dart';
enum MessageType { text, image, video, prescription }

class ChatMessage {
  final String id;
  final String senderId;
  final String receiverId;
  final String? text;
  final String? mediaUrl;
  final String? appointmentId;
  final String? animalName;
  final String? documentName;
  final String? prescriptionId;
  final String? doctorName;
  final String? patientName;
  final String? medicines;
  final DateTime? prescriptionDate;
  final MessageType type;
  final DateTime timestamp;
  
  // Professional consultation system
  final bool isAutoGenerated; // True for system-generated messages
  final bool isApprovalConfirmation; // True if this is the approval confirmation message
  final bool editableByDoctor; // Doctor can edit this message

  ChatMessage({
    required this.id,
    required this.senderId,
    required this.receiverId,
    this.text,
    this.mediaUrl,
    this.appointmentId,
    this.animalName,
    this.documentName,
    this.prescriptionId,
    this.doctorName,
    this.patientName,
    this.medicines,
    this.prescriptionDate,
    this.type = MessageType.text,
    required this.timestamp,
    this.isAutoGenerated = false,
    this.isApprovalConfirmation = false,
    this.editableByDoctor = false,
  });

  factory ChatMessage.fromMap(Map<String, dynamic> map, String id) {
    return ChatMessage(
      id: id,
      senderId: map['senderId'],
      receiverId: map['receiverId'],
      text: map['text'],
      mediaUrl: map['mediaUrl'],
      appointmentId: map['appointmentId'],
      animalName: map['animalName'],
      documentName: map['documentName'],
      prescriptionId: map['prescriptionId'],
      doctorName: map['doctorName'],
      patientName: map['patientName'],
      medicines: map['medicines'],
      prescriptionDate: map['prescriptionDate'] != null ? (map['prescriptionDate'] as Timestamp).toDate() : null,
      type: MessageType.values[map['type'] ?? 0],
      timestamp: (map['timestamp'] as Timestamp).toDate(),
      isAutoGenerated: map['isAutoGenerated'] ?? false,
      isApprovalConfirmation: map['isApprovalConfirmation'] ?? false,
      editableByDoctor: map['editableByDoctor'] ?? false,
    );
  }

  Map<String, dynamic> toMap() => {
        'senderId': senderId,
        'receiverId': receiverId,
        'text': text,
        'mediaUrl': mediaUrl,
        'appointmentId': appointmentId,
        'animalName': animalName,
        'documentName': documentName,
        'prescriptionId': prescriptionId,
        'doctorName': doctorName,
        'patientName': patientName,
        'medicines': medicines,
        'prescriptionDate': prescriptionDate,
        'type': type.index,
        'timestamp': timestamp,
        'isAutoGenerated': isAutoGenerated,
        'isApprovalConfirmation': isApprovalConfirmation,
        'editableByDoctor': editableByDoctor,
      };
}
